// Last auto-updated: 2026-04-05 09:04
// ============================================================
// Twin City Cannabis — Data Layer
// Real Twin Cities dispensary data + products + strains
// ============================================================

const TCC = window.TCC || {};

// ---- REAL DISPENSARIES ----
TCC.dispensaries = [
    {
        id: 'wildflower-5',
        name: 'Wildflower',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '326 Central Ave SE, Minneapolis, MN 55414',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.987555,
        lng: -93.253972,
        phone: '(612) 482-4842',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/wildflower-5',
        tier: 'free',
        tcc_score: 91,
        scores: { pricing: 91, selection: 92, service: 92, lab_testing: 95 },
        review_count: 14,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #581c87, #9333ea)',
        initial: 'WI',
        img: "https://images.weedmaps.com/dispensaries/000/400/574/avatar/1771615415-download.jpeg"
    },
    {
        id: 'unanimous-cannabis',
        name: 'Unanimous Cannabis',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '2835 Hennepin Ave STE C, Minneapolis, MN 55408',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.950827,
        lng: -93.298058,
        phone: '(612) 360-1723',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/unanimous-cannabis',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 92, selection: 96, service: 91, lab_testing: 95 },
        review_count: 7,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #166534, #22c55e)',
        initial: 'UC',
        img: "https://images.weedmaps.com/dispensaries/000/403/391/avatar/1771784760-weedmapsphoto2.jpg"
    },
    {
        id: 'bloomn',
        name: 'BlooMn',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '2518 central ave ne, Minneapolis, MN 55418',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 45.013811,
        lng: -93.247877,
        phone: '(612) 493-0420',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/bloomn',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 92, selection: 87, service: 95, lab_testing: 94 },
        review_count: 4,
        verified: false,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #854d0e, #ca8a04)',
        initial: 'BL',
        img: "https://images.weedmaps.com/dispensaries/000/402/784/avatar/1770400029-b2f61014-a075-46f6-a167-ab9755f73daf.PNG"
    },
    {
        id: 'lucky-strains-cannabis-dispensary',
        name: 'Lucky Strains Cannabis Dispensary',
        tagline: 'Cannabis dispensary in New Brighton',
        address: '151 Silver Lake Road NW Suite 114, New Brighton, MN 55112',
        neighborhood: 'New Brighton',
        city: 'New Brighton',
        lat: 45.05131588029472,
        lng: -93.21744781787572,
        phone: '(651) 424-6788',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/lucky-strains-cannabis-dispensary',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 85, selection: 90, service: 97, lab_testing: 86 },
        review_count: 3,
        verified: false,
        features: ["Curbside pickup"],
        gradient: 'linear-gradient(135deg, #1e40af, #60a5fa)',
        initial: 'LS',
        img: "https://images.weedmaps.com/dispensaries/000/402/233/avatar/1764889448-flow_hub_webstore_logo.png"
    },
    {
        id: 'rise-dispensaries-brooklyn-park',
        name: 'RISE Dispensaries Brooklyn Park',
        tagline: 'Cannabis dispensary in Brooklyn Park',
        address: '8016 Brooklyn Blvd, Brooklyn Park, MN 55445',
        neighborhood: 'Brooklyn Park',
        city: 'Brooklyn Park',
        lat: 45.0951,
        lng: -93.37865,
        phone: '(763) 317-6762',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/rise-dispensaries-brooklyn-park',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 85, selection: 91, service: 91, lab_testing: 87 },
        review_count: 1,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #1e40af, #60a5fa)',
        initial: 'RD',
        img: "https://images.weedmaps.com/dispensaries/000/375/408/avatar/1734453691-screen_shot_2024-12-17_at_8-41-11_am.png"
    },
    {
        id: 'loon-leaf',
        name: 'Loon Leaf',
        tagline: 'Cannabis dispensary in Blaine',
        address: '8700 university ave NE, Blaine, MN 55448',
        neighborhood: 'Blaine',
        city: 'Blaine',
        lat: 45.130637,
        lng: -93.26615,
        phone: '(763) 215-8828',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/loon-leaf',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 91, selection: 87, service: 88, lab_testing: 93 },
        review_count: 3,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #065f46, #059669)',
        initial: 'LL',
        img: "https://images.weedmaps.com/dispensaries/000/404/282/avatar/1770396120-loon_leaf_logo_with_wording__1_.png"
    },
    {
        id: 'lucid-leaf-2',
        name: 'Blaine Dispensary',
        tagline: 'Cannabis dispensary in Blaine',
        address: '1536 NE 125th Avenue, Blaine, MN 55449',
        neighborhood: 'Blaine',
        city: 'Blaine',
        lat: 45.196687,
        lng: -93.170298,
        phone: '(763) 703-4202',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/lucid-leaf-2',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 88, selection: 94, service: 94, lab_testing: 91 },
        review_count: 2,
        verified: false,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #92400e, #d97706)',
        initial: 'BD',
        img: "https://images.weedmaps.com/dispensaries/000/405/894/avatar/1773090768-black_green.png"
    },
    {
        id: 'mn-thc-co-2',
        name: 'MN THC CO - LAKEVILLE',
        tagline: 'Cannabis dispensary in Lakeville',
        address: '16085 BUCK HILL RD, Lakeville, MN 55044',
        neighborhood: 'Lakeville',
        city: 'Lakeville',
        lat: 44.717141,
        lng: -93.286261,
        phone: '(952) 388-1036',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/mn-thc-co-2',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 90, selection: 93, service: 93, lab_testing: 91 },
        review_count: 2,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #7c2d12, #dc2626)',
        initial: 'MT',
        img: "https://images.weedmaps.com/dispensaries/000/406/028/avatar/1773776180-copy_of_copy_of_copy_of_untitled_design.png"
    },
    {
        id: 'high-10-dispensary',
        name: 'High 10 Dispensary',
        tagline: 'Cannabis dispensary in Ramsey',
        address: '6111 HW10 #500, Ramsey, MN 55303',
        neighborhood: 'Ramsey',
        city: 'Ramsey',
        lat: 45.218895,
        lng: -93.422483,
        phone: '(763) 208-4062',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/high-10-dispensary',
        tier: 'free',
        tcc_score: 90,
        scores: { pricing: 88, selection: 93, service: 93, lab_testing: 88 },
        review_count: 4,
        verified: false,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #166534, #22c55e)',
        initial: 'H1',
        img: "https://images.weedmaps.com/dispensaries/000/406/386/avatar/1773867496-logo_weedmaps.png"
    },
    {
        id: 'leafline-labs-st-paul',
        name: 'RISE Dispensary St. Paul',
        tagline: 'Cannabis dispensary in Saint Paul',
        address: '2239 Ford Pkwy, Saint Paul, MN 55114',
        neighborhood: 'Saint Paul',
        city: 'Saint Paul',
        lat: 44.967043,
        lng: -93.1968394,
        phone: '(651) 313-6733',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/leafline-labs-st-paul',
        tier: 'free',
        tcc_score: 89,
        scores: { pricing: 90, selection: 88, service: 88, lab_testing: 90 },
        review_count: 13,
        verified: true,
        features: ["Curbside pickup"],
        gradient: 'linear-gradient(135deg, #065f46, #059669)',
        initial: 'RD',
        img: "https://images.weedmaps.com/static/placeholders/weedmaps-logo.jpg"
    },
    {
        id: 'legacy-cannabis',
        name: 'Legacy Cannabis Woodbury',
        tagline: 'Cannabis dispensary in Woodbury',
        address: '9891 Hudson Pl #100, Woodbury, MN 55125',
        neighborhood: 'Woodbury',
        city: 'Woodbury',
        lat: 44.944474,
        lng: -92.906832,
        phone: '(651) 421-4088',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/legacy-cannabis',
        tier: 'free',
        tcc_score: 89,
        scores: { pricing: 91, selection: 86, service: 91, lab_testing: 86 },
        review_count: 19,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #365314, #65a30d)',
        initial: 'LC',
        img: "https://images.weedmaps.com/dispensaries/000/401/126/avatar/1762059239-800x800wb_01_artboard_1.png"
    },
    {
        id: 'edina-canna',
        name: 'Edina Canna',
        tagline: 'Cannabis dispensary in Edina',
        address: '7145 France Avenue South, Edina, MN 55435',
        neighborhood: 'Edina',
        city: 'Edina',
        lat: 44.873398,
        lng: -93.328839,
        phone: '(612) 208-6509',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/edina-canna',
        tier: 'free',
        tcc_score: 87,
        scores: { pricing: 90, selection: 84, service: 90, lab_testing: 88 },
        review_count: 13,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #92400e, #d97706)',
        initial: 'EC',
        img: "https://images.weedmaps.com/dispensaries/000/401/767/avatar/1770935526-edina_canna_profile_picture.png"
    },
    {
        id: 'sweet-leaves',
        name: 'Sweetleaves',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '905 N Washington Ave, Minneapolis, MN 55401',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.989754,
        lng: -93.280123,
        phone: '(612) 688-9333',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/sweet-leaves',
        tier: 'free',
        tcc_score: 86,
        scores: { pricing: 81, selection: 92, service: 87, lab_testing: 86 },
        review_count: 5,
        verified: true,
        features: ["Online ordering", "Curbside pickup"],
        gradient: 'linear-gradient(135deg, #065f46, #059669)',
        initial: 'SW',
        img: "https://images.weedmaps.com/dispensaries/000/386/834/avatar/1762811770-sweetleaves_pic_.png"
    },
    {
        id: 'frostbite-dispensary',
        name: 'Frostbite Dispensary',
        tagline: 'Cannabis dispensary in Roseville',
        address: '2218 COUNTY ROAD D West SUITE 200, Roseville, MN 55112',
        neighborhood: 'Roseville',
        city: 'Roseville',
        lat: 45.03561082385465,
        lng: -93.19441198787388,
        phone: '(651) 440-9991',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/frostbite-dispensary',
        tier: 'free',
        tcc_score: 86,
        scores: { pricing: 88, selection: 89, service: 86, lab_testing: 89 },
        review_count: 5,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #854d0e, #ca8a04)',
        initial: 'FD',
        img: "https://images.weedmaps.com/dispensaries/000/386/867/avatar/1762796325-weedmaps_logo.jpg"
    },
    {
        id: 'dna-dispensary',
        name: 'DNA Dispensary',
        tagline: 'Cannabis dispensary in Saint Paul',
        address: '1559 Randolph Ave, Saint Paul, MN 55105',
        neighborhood: 'Saint Paul',
        city: 'Saint Paul',
        lat: 44.92716,
        lng: -93.16626,
        phone: '(651) 391-3896',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/dna-dispensary',
        tier: 'free',
        tcc_score: 86,
        scores: { pricing: 84, selection: 90, service: 90, lab_testing: 89 },
        review_count: 7,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #92400e, #d97706)',
        initial: 'DD',
        img: "https://images.weedmaps.com/dispensaries/000/399/170/avatar/1767915811-weedmaps_thumbnail.png"
    },
    {
        id: 'minnesota-canna',
        name: 'Minnesota Canna',
        tagline: 'Cannabis dispensary in Edina',
        address: '5125 Edina Industrial Blvd Suite 300, Edina, MN 55439',
        neighborhood: 'Edina',
        city: 'Edina',
        lat: 44.863465,
        lng: -93.353898,
        phone: '(952) 444-4420',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/minnesota-canna',
        tier: 'free',
        tcc_score: 86,
        scores: { pricing: 89, selection: 84, service: 89, lab_testing: 85 },
        review_count: 9,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #1e3a5f, #3b82f6)',
        initial: 'MC',
        img: "https://images.weedmaps.com/dispensaries/000/404/292/avatar/1770936812-weedmaps-profile_800x800__minnesota_canna_.png"
    },
    {
        id: 'higher-place',
        name: 'higherplace',
        tagline: 'Cannabis dispensary in Chaska',
        address: '103 W 2nd Street, Chaska, MN 55318',
        neighborhood: 'Chaska',
        city: 'Chaska',
        lat: 44.785065,
        lng: -93.600612,
        phone: '(952) 807-9944',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/higher-place',
        tier: 'free',
        tcc_score: 85,
        scores: { pricing: 80, selection: 85, service: 84, lab_testing: 82 },
        review_count: 8,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #365314, #65a30d)',
        initial: 'HI',
        img: "https://images.weedmaps.com/dispensaries/000/400/443/avatar/1773958673-leaf_alone_highres.png"
    },
    {
        id: 'strains-of-the-earth',
        name: 'Strains of the Earth',
        tagline: 'Cannabis dispensary in Jordan',
        address: '415 Broadway St S, Jordan, MN 55352',
        neighborhood: 'Jordan',
        city: 'Jordan',
        lat: 44.663405,
        lng: -93.625731,
        phone: '(952) 417-6133',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/strains-of-the-earth',
        tier: 'free',
        tcc_score: 85,
        scores: { pricing: 85, selection: 85, service: 92, lab_testing: 82 },
        review_count: 6,
        verified: true,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #365314, #65a30d)',
        initial: 'SO',
        img: "https://images.weedmaps.com/dispensaries/000/402/443/avatar/1772821717-premium_cannabis___accesories__2_.png"
    },
    {
        id: 'green-goods-woodbury',
        name: 'Green Goods - Woodbury',
        tagline: 'Cannabis dispensary in Woodbury',
        address: '803 Bielenberg Drive Building F5, Suite 101, Woodbury, MN 55125',
        neighborhood: 'Woodbury',
        city: 'Woodbury',
        lat: 44.937158,
        lng: -92.952422,
        phone: '(612) 260-1222',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/green-goods-woodbury',
        tier: 'free',
        tcc_score: 84,
        scores: { pricing: 87, selection: 81, service: 88, lab_testing: 87 },
        review_count: 7,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #166534, #22c55e)',
        initial: 'GG',
        img: "https://images.weedmaps.com/dispensaries/000/306/257/avatar/1712256112-primary-yellow-and-navy-gg-dispensary-logo-stacked-copy_1_.png"
    },
    {
        id: 'legacy-cannabis-1',
        name: 'Legacy Cannabis Minneapolis',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '2930 Lyndale Ave S, Minneapolis, MN 55408',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.94903,
        lng: -93.28852,
        phone: '(612) 418-1050',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/legacy-cannabis-1',
        tier: 'free',
        tcc_score: 83,
        scores: { pricing: 80, selection: 81, service: 82, lab_testing: 85 },
        review_count: 1,
        verified: false,
        features: ["Online ordering"],
        gradient: 'linear-gradient(135deg, #581c87, #9333ea)',
        initial: 'LC',
        img: "https://images.weedmaps.com/dispensaries/000/403/049/avatar/1766257763-mplsmobile_1600x1600wb_01_artboard_1.jpg"
    },
    {
        id: 'hopkis-dispensary',
        name: 'Hopkins Dispensary',
        tagline: 'Cannabis dispensary in Hopkins',
        address: '415 17th ave North, Hopkins, MN 55343',
        neighborhood: 'Hopkins',
        city: 'Hopkins',
        lat: 44.932193,
        lng: -93.420651,
        phone: '(612) 222-0471',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/hopkis-dispensary',
        tier: 'free',
        tcc_score: 83,
        scores: { pricing: 81, selection: 81, service: 86, lab_testing: 84 },
        review_count: 12,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #065f46, #059669)',
        initial: 'HD',
        img: "https://images.weedmaps.com/dispensaries/000/402/232/avatar/1765470161-hopkins_logo.png"
    },
    {
        id: 'anoka-cannabis-company',
        name: 'Anoka Cannabis Company',
        tagline: 'Cannabis dispensary in Anoka',
        address: '839 East River Road, Anoka, MN 55303',
        neighborhood: 'Anoka',
        city: 'Anoka',
        lat: 45.186812,
        lng: -93.374843,
        phone: '(763) 576-2967',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/anoka-cannabis-company',
        tier: 'free',
        tcc_score: 82,
        scores: { pricing: 85, selection: 80, service: 88, lab_testing: 79 },
        review_count: 5,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #92400e, #d97706)',
        initial: 'AC',
        img: "https://images.weedmaps.com/dispensaries/000/404/749/avatar/1770330973-acc-round-logo.jpg"
    },
    {
        id: 'minnesota-medical-solutions',
        name: 'Green Goods - Minneapolis',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '207 9th St, Minneapolis, MN 55402',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.973289,
        lng: -93.27089,
        phone: '(612) 999-1615',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/minnesota-medical-solutions',
        tier: 'free',
        tcc_score: 81,
        scores: { pricing: 84, selection: 78, service: 88, lab_testing: 82 },
        review_count: 34,
        verified: true,
        features: ["Curbside pickup"],
        gradient: 'linear-gradient(135deg, #854d0e, #ca8a04)',
        initial: 'GG',
        img: "https://images.weedmaps.com/dispensaries/000/044/502/avatar/1712256066-primary-yellow-and-navy-gg-dispensary-logo-stacked-copy_1_.png"
    },
    {
        id: 'minnesota-medical-solutions-bloomington',
        name: 'Green Goods - Bloomington',
        tagline: 'Cannabis dispensary in Bloomington',
        address: '5232 W. 84th Street, Bloomington, MN 55437',
        neighborhood: 'Bloomington',
        city: 'Bloomington',
        lat: 44.852685,
        lng: -93.346609,
        phone: '(952) 800-4404',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/minnesota-medical-solutions-bloomington',
        tier: 'free',
        tcc_score: 81,
        scores: { pricing: 84, selection: 80, service: 85, lab_testing: 85 },
        review_count: 23,
        verified: true,
        features: ["Curbside pickup"],
        gradient: 'linear-gradient(135deg, #365314, #65a30d)',
        initial: 'GG',
        img: "https://images.weedmaps.com/dispensaries/000/049/724/avatar/1712255971-primary-yellow-and-navy-gg-dispensary-logo-stacked-copy_1_.png"
    },
    {
        id: 'green-goods-blaine',
        name: 'Green Goods - Blaine',
        tagline: 'Cannabis dispensary in Blaine',
        address: '672 County Highway 10 Northcourt Commons, Blaine, MN 55434',
        neighborhood: 'Blaine',
        city: 'Blaine',
        lat: 45.12688,
        lng: -93.253947,
        phone: '(763) 400-4777',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/green-goods-blaine',
        tier: 'free',
        tcc_score: 78,
        scores: { pricing: 79, selection: 76, service: 80, lab_testing: 79 },
        review_count: 6,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #4338ca, #7c3aed)',
        initial: 'GG',
        img: "https://images.weedmaps.com/dispensaries/000/306/254/avatar/1712255555-primary-yellow-and-navy-gg-dispensary-logo-stacked-copy_1_.png"
    },
    {
        id: 'green-goods-burnsville',
        name: 'Green Goods - Burnsville',
        tagline: 'Cannabis dispensary in Burnsville',
        address: '14334 Burnhaven Drive Suite 14334, Burnsville, MN 55306',
        neighborhood: 'Burnsville',
        city: 'Burnsville',
        lat: 44.74213,
        lng: -93.294789,
        phone: '(952) 856-8603',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/green-goods-burnsville',
        tier: 'free',
        tcc_score: 78,
        scores: { pricing: 81, selection: 83, service: 78, lab_testing: 79 },
        review_count: 6,
        verified: true,
        features: [],
        gradient: 'linear-gradient(135deg, #854d0e, #ca8a04)',
        initial: 'GG',
        img: "https://images.weedmaps.com/dispensaries/000/306/256/avatar/1712256011-primary-yellow-and-navy-gg-dispensary-logo-stacked-copy_1_.png"
    },
    {
        id: 'legit-cannabis',
        name: 'Legit Cannabis',
        tagline: 'Cannabis dispensary in Rosemount',
        address: '16000 Cedar Ave, Rosemount, MN 55068',
        neighborhood: 'Rosemount',
        city: 'Rosemount',
        lat: 44.716752,
        lng: -93.217069,
        phone: '(952) 236-0638',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/legit-cannabis',
        tier: 'free',
        tcc_score: 76,
        scores: { pricing: 76, selection: 76, service: 79, lab_testing: 80 },
        review_count: 2,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #854d0e, #ca8a04)',
        initial: 'LC',
        img: "https://images.weedmaps.com/dispensaries/000/406/029/avatar/1773584507-square-mural.png"
    },
    {
        id: 'leafline-labs-eagan',
        name: 'RISE Dispensary Eagan',
        tagline: 'Cannabis dispensary in Eagan',
        address: '1340 Town Centre Dr, Eagan, MN 55123',
        neighborhood: 'Eagan',
        city: 'Eagan',
        lat: 44.831012,
        lng: -93.163381,
        phone: '(651) 846-9245',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/leafline-labs-eagan',
        tier: 'free',
        tcc_score: 71,
        scores: { pricing: 70, selection: 71, service: 76, lab_testing: 70 },
        review_count: 9,
        verified: true,
        features: ["Curbside pickup"],
        gradient: 'linear-gradient(135deg, #1e40af, #60a5fa)',
        initial: 'RD',
        img: "https://images.weedmaps.com/static/placeholders/weedmaps-logo.jpg"
    },
    {
        id: 'wildflower-north-loop-1',
        name: 'Wildflower North Loop',
        tagline: 'Cannabis dispensary in Minneapolis',
        address: '212 N 2nd St Suite 103, Minneapolis, MN 55401',
        neighborhood: 'Minneapolis',
        city: 'Minneapolis',
        lat: 44.985158,
        lng: -93.270461,
        phone: '(952) 250-6356',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/wildflower-north-loop-1',
        tier: 'free',
        tcc_score: 70,
        scores: { pricing: 72, selection: 72, service: 70, lab_testing: 74 },
        review_count: 0,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #7c2d12, #dc2626)',
        initial: 'WN',
        img: "https://images.weedmaps.com/dispensaries/000/405/457/avatar/1773250598-wildflower_logo_notext_930x1000.png"
    },
    {
        id: 'bloom-wellness-dispensary-st-paul',
        name: 'Bloom Wellness Dispensary - St Paul',
        tagline: 'Cannabis dispensary in Saint Paul',
        address: '550 Vandalia Street #175, Saint Paul, MN 55114',
        neighborhood: 'Saint Paul',
        city: 'Saint Paul',
        lat: 44.958082,
        lng: -93.191227,
        phone: '(651) 760-0420',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/bloom-wellness-dispensary-st-paul',
        tier: 'free',
        tcc_score: 70,
        scores: { pricing: 70, selection: 70, service: 77, lab_testing: 71 },
        review_count: 0,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #1e3a5f, #3b82f6)',
        initial: 'BW',
        img: "https://images.weedmaps.com/static/placeholders/weedmaps-logo.jpg"
    },
    {
        id: 'leafline-labs-willmar',
        name: 'RISE Dispensary Willmar',
        tagline: 'Cannabis dispensary in Eagan',
        address: '1413 1st Street S, Eagan, MN 55121',
        neighborhood: 'Eagan',
        city: 'Eagan',
        lat: 44.855434,
        lng: -93.168072,
        phone: '(320) 208-9081',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/leafline-labs-willmar',
        tier: 'free',
        tcc_score: 70,
        scores: { pricing: 70, selection: 70, service: 71, lab_testing: 73 },
        review_count: 0,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #9f1239, #e11d48)',
        initial: 'RD',
        img: "https://images.weedmaps.com/static/placeholders/weedmaps-logo.jpg"
    },
    {
        id: 'green-box-cannabis',
        name: 'Green Box Cannabis',
        tagline: 'Cannabis dispensary in Lakeville',
        address: '16350 Kenrick Loop Ste D, Lakeville, MN 55044',
        neighborhood: 'Lakeville',
        city: 'Lakeville',
        lat: 44.712549,
        lng: -93.282728,
        phone: '(651) 366-1581',
        hours: { weekday: '10am-8pm', weekend: '10am-6pm', note: 'Hours vary, check website' },
        website: 'https://weedmaps.com/dispensaries/green-box-cannabis',
        tier: 'free',
        tcc_score: 70,
        scores: { pricing: 70, selection: 73, service: 74, lab_testing: 73 },
        review_count: 0,
        verified: false,
        features: [],
        gradient: 'linear-gradient(135deg, #1e3a5f, #3b82f6)',
        initial: 'GB',
        img: "https://images.weedmaps.com/dispensaries/000/406/475/avatar/1773964027-green_box.jpg"
    }
];

// ---- STRAINS ----
TCC.strains = [
    { id: 'blue-dream', name: 'Blue Dream', type: 'hybrid', thc: '21-24%', cbd: '<1%', effects: ['Relaxed', 'Happy', 'Euphoric', 'Creative'], flavors: ['Berry', 'Sweet', 'Herbal'], desc: 'A balanced hybrid offering full-body relaxation with gentle cerebral invigoration.' },
    { id: 'northern-lights', name: 'Northern Lights', type: 'indica', thc: '18-22%', cbd: '<1%', effects: ['Relaxed', 'Sleepy', 'Happy', 'Euphoric'], flavors: ['Pine', 'Earthy', 'Sweet'], desc: 'One of the most famous indicas, prized for its resinous buds and fast flowering.' },
    { id: 'sour-diesel', name: 'Sour Diesel', type: 'sativa', thc: '20-25%', cbd: '<1%', effects: ['Energetic', 'Happy', 'Uplifted', 'Creative'], flavors: ['Diesel', 'Pungent', 'Earthy'], desc: 'A fast-acting sativa with dreamy, energizing effects and a pungent diesel aroma.' },
    { id: 'girl-scout-cookies', name: 'Girl Scout Cookies', type: 'hybrid', thc: '25-28%', cbd: '<1%', effects: ['Euphoric', 'Relaxed', 'Happy', 'Creative'], flavors: ['Sweet', 'Earthy', 'Pungent'], desc: 'A potent hybrid with a sweet, earthy aroma and powerful full-body effects.' },
    { id: 'wedding-cake', name: 'Wedding Cake', type: 'indica', thc: '24-27%', cbd: '<1%', effects: ['Relaxed', 'Euphoric', 'Happy', 'Sleepy'], flavors: ['Sweet', 'Vanilla', 'Earthy'], desc: 'Rich, tangy flavor with relaxing and euphoric effects. Great for evening use.' },
    { id: 'og-kush', name: 'OG Kush', type: 'hybrid', thc: '20-25%', cbd: '<1%', effects: ['Relaxed', 'Euphoric', 'Happy', 'Uplifted'], flavors: ['Earthy', 'Pine', 'Woody'], desc: 'The backbone of West Coast cannabis, delivering heavy euphoria and relaxation.' },
    { id: 'gelato', name: 'Gelato', type: 'hybrid', thc: '22-26%', cbd: '<1%', effects: ['Relaxed', 'Euphoric', 'Happy', 'Creative'], flavors: ['Sweet', 'Citrus', 'Berry'], desc: 'Dessert-like flavor with a balanced, feel-good high. Beautiful purple buds.' },
    { id: 'purple-haze', name: 'Purple Haze', type: 'sativa', thc: '17-20%', cbd: '<1%', effects: ['Euphoric', 'Happy', 'Creative', 'Energetic'], flavors: ['Berry', 'Earthy', 'Sweet'], desc: 'A legendary sativa delivering creative energy and blissful contentment.' },
    { id: 'jack-herer', name: 'Jack Herer', type: 'sativa', thc: '18-23%', cbd: '<1%', effects: ['Happy', 'Uplifted', 'Energetic', 'Creative'], flavors: ['Pine', 'Earthy', 'Woody'], desc: 'Named after the cannabis activist, this sativa is a blissful, clear-headed staple.' },
    { id: 'granddaddy-purple', name: 'Granddaddy Purple', type: 'indica', thc: '20-24%', cbd: '<1%', effects: ['Relaxed', 'Sleepy', 'Happy', 'Euphoric'], flavors: ['Grape', 'Berry', 'Sweet'], desc: 'A famous indica with a complex grape and berry aroma. Deep physical relaxation.' },
    { id: 'green-crack', name: 'Green Crack', type: 'sativa', thc: '17-21%', cbd: '<1%', effects: ['Energetic', 'Focused', 'Happy', 'Uplifted'], flavors: ['Citrus', 'Sweet', 'Mango'], desc: 'Tangy mango flavor with an invigorating mental buzz. Perfect for daytime.' },
    { id: 'gorilla-glue', name: 'Gorilla Glue #4', type: 'hybrid', thc: '25-30%', cbd: '<1%', effects: ['Relaxed', 'Euphoric', 'Happy', 'Uplifted'], flavors: ['Pine', 'Earthy', 'Pungent'], desc: 'Heavy-handed euphoria that glues you to the couch. Multiple award winner.' },
    { id: 'white-widow', name: 'White Widow', type: 'hybrid', thc: '18-22%', cbd: '<1%', effects: ['Euphoric', 'Energetic', 'Creative', 'Happy'], flavors: ['Earthy', 'Woody', 'Pungent'], desc: 'A balanced hybrid known worldwide for its white crystal resin and burst of energy.' },
    { id: 'pineapple-express', name: 'Pineapple Express', type: 'hybrid', thc: '19-24%', cbd: '<1%', effects: ['Happy', 'Uplifted', 'Euphoric', 'Relaxed'], flavors: ['Tropical', 'Pineapple', 'Sweet'], desc: 'A tropical, citrusy hybrid perfect for productive afternoons.' },
    { id: 'runtz', name: 'Runtz', type: 'hybrid', thc: '24-29%', cbd: '<1%', effects: ['Euphoric', 'Relaxed', 'Happy', 'Tingly'], flavors: ['Fruity', 'Candy', 'Sweet'], desc: 'Candy-like sweetness with a perfectly balanced high.' },
    { id: 'zkittlez', name: 'Zkittlez', type: 'indica', thc: '20-23%', cbd: '<1%', effects: ['Relaxed', 'Happy', 'Euphoric', 'Sleepy'], flavors: ['Sweet', 'Tropical', 'Berry'], desc: 'Taste the rainbow. A flavorful indica with a calm, happy buzz.' },
];

// ---- CATEGORIES ----
TCC.categories = [
    { id: 'flower', name: 'Flower', icon: '&#127807;' },
    { id: 'pre-roll', name: 'Pre-Rolls', icon: '&#128684;' },
    { id: 'cartridge', name: 'Cartridges', icon: '&#128267;' },
    { id: 'edible', name: 'Edibles', icon: '&#127850;' },
    { id: 'concentrate', name: 'Concentrates', icon: '&#128142;' },
    { id: 'topical', name: 'Topicals', icon: '&#128167;' },
    { id: 'tincture', name: 'Tinctures', icon: '&#129514;' },
    { id: 'beverage', name: 'Beverages', icon: '&#127864;' },
];

// ---- PRODUCTS ----
TCC.products = [
    { id: 'p001', name: 'Campfire Cannabis - 4g Flower - Grape Cream Cake (I/H)', brand: 'Unknown', category: 'flower', strain: null, weight: '', thc: '', cbd: '',
      prices: { 'legacy-cannabis-mpls': 48.0 },
      priceHistory: [53, 52, 51, 50, 49, 48, 48, 48.0] },
    { id: 'p002', name: 'Dark Rainbow', brand: 'Unknown', category: 'flower', strain: null, weight: '', thc: '26.8%', cbd: '',
      prices: { 'sweetleaves-north-loop': 58.0 },
      priceHistory: [64, 63, 62, 61, 60, 59, 58, 58.0] },
    { id: 'p003', name: 'Gary Payton (Limited Edition) - 28g', brand: 'Unknown', category: 'flower', strain: null, weight: '', thc: '20.4%', cbd: '',
      prices: { 'legacy-cannabis-mpls': 300.0 },
      priceHistory: [336, 330, 324, 318, 312, 306, 303, 300.0] },
    { id: 'p004', name: 'Hawaiian Fanta', brand: 'Unknown', category: 'flower', strain: null, weight: '', thc: '26.5%', cbd: '',
      prices: { 'sweetleaves-north-loop': 58.0 },
      priceHistory: [64, 63, 62, 61, 60, 59, 58, 58.0] },
    { id: 'p005', name: 'Super Boof', brand: 'Unknown', category: 'flower', strain: null, weight: '', thc: '', cbd: '',
      prices: { 'sweetleaves-north-loop': 62.0 },
      priceHistory: [69, 68, 66, 65, 64, 63, 62, 62.0] }
];

// ---- DEALS ----
TCC.deals = [
    { id: 'd001', dispensaryId: 'sweetleaves-north-loop', productId: 'p001', title: '20% Off Blue Dream', type: 'percent-off', discount: 20, originalPrice: 42, salePrice: 34, expires: '2026-04-12', featured: true },
    { id: 'd002', dispensaryId: 'nativecare-wsp', productId: 'p011', title: 'Pre-Roll 5pk Flash Sale', type: 'flash', discount: 30, originalPrice: 40, salePrice: 28, expires: '2026-04-06', featured: true },
    { id: 'd003', dispensaryId: 'green-goods-mpls', productId: 'p017', title: 'Edible Weekend Special', type: 'percent-off', discount: 15, originalPrice: 28, salePrice: 24, expires: '2026-04-07', featured: false },
    { id: 'd004', dispensaryId: 'legacy-cannabis-mpls', productId: null, title: 'First-Time Customer 25% Off', type: 'new-customer', discount: 25, originalPrice: null, salePrice: null, expires: '2026-06-30', featured: true },
    { id: 'd005', dispensaryId: 'budtales-mpls', productId: 'p024', title: 'Concentrate Day: $10 Off Wax', type: 'dollar-off', discount: 10, originalPrice: 55, salePrice: 45, expires: '2026-04-08', featured: false },
    { id: 'd006', dispensaryId: 'sweetleaves-north-loop', productId: null, title: 'Happy Hour 4-6pm: 15% Off Carts', type: 'happy-hour', discount: 15, originalPrice: null, salePrice: null, expires: '2026-04-30', featured: true },
    { id: 'd007', dispensaryId: 'edina-canna', productId: 'p007', title: 'GSC 3.5g Price Drop', type: 'price-drop', discount: null, originalPrice: 55, salePrice: 50, expires: '2026-04-10', featured: false },
    { id: 'd008', dispensaryId: 'nativecare-wsp', productId: null, title: 'Veterans 20% Off Every Day', type: 'veteran', discount: 20, originalPrice: null, salePrice: null, expires: null, featured: false },
    { id: 'd009', dispensaryId: 'legacy-cannabis-woodbury', productId: 'p014', title: 'Northern Lights Cart BOGO 50%', type: 'bogo', discount: 50, originalPrice: 46, salePrice: 46, expires: '2026-04-09', featured: true },
    { id: 'd010', dispensaryId: 'edina-canna', productId: 'p018', title: 'Gummies 2-for-1', type: 'bogo', discount: 100, originalPrice: 18, salePrice: 18, expires: '2026-04-11', featured: true },
    { id: 'd011', dispensaryId: 'budtales-mpls', productId: null, title: 'Loyalty Points 2x Weekend', type: 'loyalty', discount: null, originalPrice: null, salePrice: null, expires: '2026-04-07', featured: false },
    { id: 'd012', dispensaryId: 'sweetleaves-north-loop', productId: 'p009', title: 'Runtz Drop: Limited Batch', type: 'new-arrival', discount: null, originalPrice: null, salePrice: 52, expires: '2026-04-15', featured: true },
];

// ---- REVIEWS ----
TCC.reviews = [
    { dispensaryId: 'sweetleaves-north-loop', author: 'Mike T.', date: '2026-03-28', rating: 5, text: 'Absolutely stunning space. The staff is incredibly knowledgeable and the product selection is the best in the Twin Cities. Worth every penny.' },
    { dispensaryId: 'sweetleaves-north-loop', author: 'Sarah K.', date: '2026-03-25', rating: 5, text: 'Love that they accept credit cards and have delivery. Pet-friendly is a huge plus. Premium brands you can\'t find anywhere else.' },
    { dispensaryId: 'sweetleaves-north-loop', author: 'Chris L.', date: '2026-03-20', rating: 4, text: 'Great dispensary, prices are on the higher side but the quality and experience make up for it. North Loop location is perfect.' },
    { dispensaryId: 'green-goods-mpls', author: 'Jenna R.', date: '2026-03-30', rating: 5, text: 'Downtown location is super convenient. Love the online ordering, in and out in 5 minutes. Lab testing transparency is impressive.' },
    { dispensaryId: 'green-goods-mpls', author: 'Dave M.', date: '2026-03-22', rating: 4, text: 'Been coming here since they were medical-only. The transition to rec has been smooth. Consistently good quality flower.' },
    { dispensaryId: 'budtales-mpls', author: 'Amy N.', date: '2026-03-29', rating: 5, text: 'Best delivery service in Minneapolis. Always on time, great communication. Full menu and competitive prices.' },
    { dispensaryId: 'budtales-mpls', author: 'Tom H.', date: '2026-03-24', rating: 4, text: 'Solid downtown option. Big selection, lab-tested everything. Can\'t ask for much more.' },
    { dispensaryId: 'legacy-cannabis-mpls', author: 'Maria G.', date: '2026-03-27', rating: 4, text: 'Great flower selection and the artisan glass is a nice touch. Lyndale location is easy to get to.' },
    { dispensaryId: 'zaza-st-paul', author: 'Kevin P.', date: '2026-03-26', rating: 4, text: 'Nice neighborhood shop on Grand Ave. Good prices on edibles, friendly staff.' },
    { dispensaryId: 'nativecare-wsp', author: 'Lisa W.', date: '2026-03-21', rating: 5, text: 'Love supporting a tribal dispensary. Prices are competitive and the staff is really welcoming.' },
    { dispensaryId: 'edina-canna', author: 'Ryan J.', date: '2026-03-23', rating: 4, text: 'Clean, professional suburban dispensary. Good selection of premium brands. Parking is easy.' },
    { dispensaryId: 'minnesota-dispensary-sp', author: 'Pat S.', date: '2026-03-19', rating: 4, text: 'Convenient having so many locations. Consistent quality across stores. Online ordering works great.' },
];

// ---- HELPER FUNCTIONS ----
TCC.getDispensary = (id) => TCC.dispensaries.find(d => d.id === id);
TCC.getProduct = (id) => TCC.products.find(p => p.id === id);
TCC.getStrain = (id) => TCC.strains.find(s => s.id === id);

TCC.getLowestPrice = (product) => {
    const entries = Object.entries(product.prices);
    if (!entries.length) return null;
    return entries.reduce((min, [id, price]) => price < min.price ? { dispensaryId: id, price } : min, { dispensaryId: entries[0][0], price: entries[0][1] });
};

TCC.getHighestPrice = (product) => {
    const entries = Object.entries(product.prices);
    if (!entries.length) return null;
    return entries.reduce((max, [id, price]) => price > max.price ? { dispensaryId: id, price } : max, { dispensaryId: entries[0][0], price: entries[0][1] });
};

TCC.getPriceRange = (product) => {
    const low = TCC.getLowestPrice(product);
    const high = TCC.getHighestPrice(product);
    return { low: low?.price, high: high?.price };
};

TCC.getProductsForDispensary = (dispensaryId) => TCC.products.filter(p => p.prices[dispensaryId] !== undefined);
TCC.getDealsForDispensary = (dispensaryId) => TCC.deals.filter(d => d.dispensaryId === dispensaryId);
TCC.getReviewsForDispensary = (dispensaryId) => TCC.reviews.filter(r => r.dispensaryId === dispensaryId);
TCC.getProductsByCategory = (category) => TCC.products.filter(p => p.category === category);
TCC.getProductsByStrain = (strainId) => TCC.products.filter(p => p.strain === strainId);

TCC.searchProducts = (query) => {
    const q = query.toLowerCase();
    return TCC.products.filter(p =>
        p.name.toLowerCase().includes(q) ||
        p.brand.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q) ||
        (p.strain && TCC.getStrain(p.strain)?.name.toLowerCase().includes(q))
    );
};

TCC.searchDispensaries = (query) => {
    const q = query.toLowerCase();
    return TCC.dispensaries.filter(d =>
        d.name.toLowerCase().includes(q) ||
        d.neighborhood.toLowerCase().includes(q) ||
        d.city.toLowerCase().includes(q)
    );
};

TCC.formatPrice = (price) => `$${price}`;
TCC.getTierLabel = (tier) => ({ free: '', featured: 'Featured', premium: 'Premium', platinum: 'Platinum Partner' }[tier] || '');
TCC.getTierColor = (tier) => ({ free: '', featured: '#22c55e', premium: '#a855f7', platinum: '#f59e0b' }[tier] || '');
TCC.getScoreColor = (score) => score >= 90 ? '#22c55e' : score >= 80 ? '#f59e0b' : score >= 70 ? '#f97316' : '#ef4444';
TCC.getScoreLabel = (score) => score >= 90 ? 'Excellent' : score >= 80 ? 'Great' : score >= 70 ? 'Good' : 'Fair';
TCC.priceHistoryLabels = ['8w ago', '7w ago', '6w ago', '5w ago', '4w ago', '3w ago', '2w ago', 'Now'];

// ---- MINNESOTA-GROWN BRANDS ----
TCC.mnBrands = [
    { name: 'Roots & Resin Farms', location: 'Lindstrom, MN', type: 'Cultivator', specialty: 'Solventless rosin extracts', desc: 'One of Minnesota\'s first licensed recreational cultivators, focused on premium solventless concentrates.' },
    { name: 'Concentrate Labs', location: 'Lindstrom, MN', type: 'Cultivator', specialty: 'Craft flower & concentrates', desc: 'Minnesota\'s second licensed cultivator. Seeds in the ground since day one.' },
    { name: 'M.N. Technology', location: 'Cohasset, MN', type: 'Cultivator & Processor', specialty: 'Wholesale distribution', desc: 'Produces and packages cannabis for wholesale distribution throughout Minnesota.' },
    { name: 'CANN', location: 'National (sold in MN)', type: 'Beverage', specialty: 'Social tonics', desc: 'Low-dose cannabis beverages. Available at Sweetleaves and other premium dispensaries.' },
    { name: 'Nowadays', location: 'National (sold in MN)', type: 'Beverage', specialty: 'THC sparkling water', desc: 'Sessionable THC beverages available across Twin Cities dispensaries.' },
    { name: 'Gigli', location: 'MN brand', type: 'Edibles', specialty: 'Premium gummies', desc: 'Craft cannabis gummies available at select Twin Cities locations.' },
    { name: 'Mary & Jane', location: 'MN brand', type: 'Edibles & Flower', specialty: 'Full spectrum products', desc: 'Minnesota-made cannabis products with full spectrum formulations.' },
];

// ---- COMING SOON DISPENSARIES ----
TCC.comingSoon = [
    { name: 'Anoka Cannabis Company', location: 'Anoka, MN', type: 'Municipal', status: 'Opening 2026', desc: 'Minnesota\'s first government-run cannabis dispensary. City-owned and operated.', notable: 'First municipal dispensary in the US' },
    { name: 'Osseo Municipal Dispensary', location: 'Osseo, MN', type: 'Municipal', status: 'Mid-2026', desc: 'Osseo\'s publicly run dispensary, currently in renovation and licensing phase.', notable: 'City-operated' },
    { name: 'RISE Brooklyn Park', location: 'Brooklyn Park, MN', type: 'Retail', status: 'Expanding', desc: 'RISE dispensary expanding adult-use sales at their Brooklyn Park location.', notable: 'Part of Green Thumb Industries' },
    { name: 'Green Goods Bloomington', location: 'Bloomington, MN', type: 'Retail', status: 'Adult-use expansion', desc: 'Green Goods adding full adult-use menu at their Bloomington location.', notable: 'Medical to recreational transition' },
    { name: 'RISE Eagan', location: 'Eagan, MN', type: 'Retail', status: 'Expanding', desc: 'RISE dispensary expanding adult-use product line in Eagan.', notable: 'South metro location' },
];

// ---- TCC SHOP MERCH ----
TCC.shopItems = [
    { name: 'TCC Snapback Hat', price: 34, category: 'headwear', img: null, status: 'coming-soon', desc: 'Embroidered logo, structured fit. Black/green.' },
    { name: 'TCC Heavyweight Hoodie', price: 68, category: 'apparel', img: null, status: 'coming-soon', desc: 'Oversized cut, puff print logo. Premium heavyweight fleece.' },
    { name: 'TCC Graphic Tee', price: 32, category: 'apparel', img: null, status: 'coming-soon', desc: 'Comfort Colors blank, subtle chest logo. Multiple colorways.' },
    { name: 'UV Stash Jar', price: 24, category: 'accessories', img: null, status: 'coming-soon', desc: 'Matte black UV glass with TCC logo. Keeps it fresh.' },
    { name: 'Metal Rolling Tray', price: 28, category: 'accessories', img: null, status: 'coming-soon', desc: 'Custom TCC art. Twin Cities skyline design.' },
    { name: 'Enamel Pin Set', price: 16, category: 'accessories', img: null, status: 'coming-soon', desc: 'Collectible 3-pack. Minneapolis landmarks + leaf motifs.' },
    { name: 'Die-Cut Sticker Pack', price: 12, category: 'accessories', img: null, status: 'available', desc: '6-pack of premium vinyl stickers. Weather-resistant.' },
    { name: 'Heavyweight Tote', price: 22, category: 'accessories', img: null, status: 'coming-soon', desc: 'Canvas tote, screenprinted. Your dispensary run bag.' },
    { name: 'Strain Journal', price: 18, category: 'accessories', img: null, status: 'coming-soon', desc: 'Moleskin-style notebook. Log strains, effects, ratings.' },
    { name: 'TCC Lighter Sleeve', price: 8, category: 'accessories', img: null, status: 'coming-soon', desc: 'Leather sleeve, fits standard Bic. Embossed logo.' },
];

window.TCC = TCC;
