#!/usr/bin/env node
/**
 * Twin City Cannabis — Jane (iHeartJane) menu scraper
 *
 * Uses Puppeteer with stealth to load a dispensary's Jane-powered menu page,
 * intercepts the dmerch API response containing the full product catalog,
 * and outputs JSON to stdout.
 *
 * Why headless browser? Jane uses FingerprintJS + Cloudflare to block direct
 * API calls. The dmerch.iheartjane.com endpoint requires a valid device ID
 * generated by the page's JavaScript. Only a real browser session works.
 *
 * Usage:
 *   node scraper/jane_scrape.js <menu_url> [--output file.json]
 *
 * Example:
 *   node scraper/jane_scrape.js "https://visitgreengoods.com/minneapolis-mn-menu-rec/"
 *   node scraper/jane_scrape.js "https://visitgreengoods.com/minneapolis-mn-menu-rec/" --output gg-mpls-rec.json
 *
 * The output JSON is an array of products with: name, brand, category, price,
 * weight, thc, image_url — ready to merge into TCC's data pipeline.
 */

const path = require("path");

// Resolve modules from the repo's node_modules (works on both Mac and Pi)
const modulesDir = path.join(__dirname, "..", "node_modules");
const puppeteer = require(path.join(modulesDir, "puppeteer-extra"));
const StealthPlugin = require(path.join(modulesDir, "puppeteer-extra-plugin-stealth"));
const fs = require("fs");

puppeteer.use(StealthPlugin());

const CHROMIUM_PATHS = [
  "/usr/bin/chromium",                                           // Pi / Debian
  "/usr/bin/chromium-browser",                                   // Ubuntu
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", // macOS
];

function findChromium() {
  for (const p of CHROMIUM_PATHS) {
    if (fs.existsSync(p)) return p;
  }
  throw new Error("No Chromium/Chrome found. Install chromium or set CHROMIUM_PATH.");
}

async function scrapeJaneMenu(menuUrl, options = {}) {
  const { timeout = 45000, scrollWait = 3000, maxScrolls = 10 } = options;

  const browser = await puppeteer.launch({
    executablePath: process.env.CHROMIUM_PATH || findChromium(),
    headless: "new",
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--disable-background-timer-throttling",
    ],
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1440, height: 900 });

    // Collect all dmerch product responses
    let catalogData = null;
    page.on("response", async (resp) => {
      const url = resp.url();
      if (url.includes("dmerch.iheartjane.com") && url.includes("/v2/multi")) {
        try {
          const text = await resp.text();
          if (text.length > 1000) {
            catalogData = text;
          }
        } catch {}
      }
    });

    console.error(`Loading ${menuUrl}...`);
    await page.goto(menuUrl, { waitUntil: "domcontentloaded", timeout });

    // Wait for the dmerch response to arrive
    const startWait = Date.now();
    while (!catalogData && Date.now() - startWait < 30000) {
      await new Promise((r) => setTimeout(r, 1000));
    }

    if (!catalogData) {
      // Try scrolling to trigger loading
      for (let i = 0; i < maxScrolls && !catalogData; i++) {
        await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
        await new Promise((r) => setTimeout(r, scrollWait));
      }
    }

    if (!catalogData) {
      console.error("No product data received from dmerch API");
      return [];
    }

    console.error(`Received ${catalogData.length} bytes from dmerch API`);

    const parsed = JSON.parse(catalogData);

    // The multi endpoint returns { placements: [{ products: [...] }, ...] }
    let allProducts = [];
    if (parsed.placements && Array.isArray(parsed.placements)) {
      for (const placement of parsed.placements) {
        if (placement.products && Array.isArray(placement.products)) {
          allProducts = allProducts.concat(placement.products);
        }
      }
    } else if (parsed.products && Array.isArray(parsed.products)) {
      allProducts = parsed.products;
    }

    console.error(`Extracted ${allProducts.length} raw products`);

    // Normalize to TCC format
    const products = allProducts.map((p) => {
      const attrs = p.search_attributes || p;

      // Price: Jane nests prices in search_attributes.bucket_price or price_each/price_half_gram etc.
      let price = 0;
      let weight = "";

      // Try bucket_price first (most common)
      if (attrs.bucket_price) {
        price = parseFloat(attrs.bucket_price) || 0;
      }

      // Available weights gives us the size options
      const availWeights = attrs.available_weights || [];
      if (availWeights.length > 0) {
        weight = availWeights[0]; // first weight is usually the default
      }

      // Price tiers — Jane stores these as price_each, price_half_gram, etc.
      if (!price) {
        const priceFields = [
          "price_each",
          "price_half_gram",
          "price_gram",
          "price_eighth",
          "price_quarter",
          "price_half_ounce",
          "price_ounce",
        ];
        for (const f of priceFields) {
          if (attrs[f] && parseFloat(attrs[f]) > 0) {
            price = parseFloat(attrs[f]);
            weight = f.replace("price_", "").replace(/_/g, " ");
            break;
          }
        }
      }

      // Category mapping
      const kind = (attrs.kind || attrs.category || "").toLowerCase();
      let category = "flower";
      if (/vape|cartridge|disposable|pod|pen/i.test(kind)) category = "cartridge";
      else if (/edible|gumm|chocolate|candy|chew/i.test(kind)) category = "edible";
      else if (/pre.?roll|joint|blunt/i.test(kind)) category = "pre-roll";
      else if (/drink|beverage|seltzer|soda|tonic/i.test(kind)) category = "beverage";
      else if (/tincture|oil|spray|tablet|capsule/i.test(kind)) category = "tincture";
      else if (/topical|balm|salve|lotion|cream/i.test(kind)) category = "topical";
      else if (/concentrate|wax|shatter|resin|rosin|dab|badder|sauce/i.test(kind)) category = "concentrate";
      else if (/flower|bud|nug|shake|ground/i.test(kind)) category = "flower";

      return {
        name: attrs.name || attrs.product_name || "",
        brand: attrs.brand || "",
        category,
        kind: attrs.kind || "",
        thc: attrs.percent_thc ? `${attrs.percent_thc}%` : "",
        cbd: attrs.percent_cbd ? `${attrs.percent_cbd}%` : "",
        price,
        weight,
        available_weights: availWeights,
        image: attrs.image_url || attrs.photo || "",
        jane_product_id: p.product_id || attrs.product_id || null,
      };
    }).filter((p) => p.name && p.price > 0);

    console.error(`Normalized ${products.length} products with prices`);
    return products;
  } finally {
    await browser.close();
  }
}

// ─── CLI ─────────────────────────────────────────────────────────────────────
if (require.main === module) {
  const args = process.argv.slice(2);
  const url = args.find((a) => !a.startsWith("--"));
  const outputIdx = args.indexOf("--output");
  const outputFile = outputIdx >= 0 ? args[outputIdx + 1] : null;

  if (!url) {
    console.error("Usage: node scraper/jane_scrape.js <menu_url> [--output file.json]");
    process.exit(1);
  }

  scrapeJaneMenu(url)
    .then((products) => {
      const json = JSON.stringify(products, null, 2);
      if (outputFile) {
        fs.writeFileSync(outputFile, json);
        console.error(`Wrote ${products.length} products to ${outputFile}`);
      } else {
        process.stdout.write(json);
      }
    })
    .catch((e) => {
      console.error("Fatal:", e.message);
      process.exit(1);
    });
}

module.exports = { scrapeJaneMenu };
